var duyuru = [
    {
        "Başlık":"basşılk",
        "Açıklama":"açıklams"
    },
    {
        "Başlık":"basşılk",
        "Açıklama":"açıklams"
    },
    {
        "Başlık":"basşılk",
        "Açıklama":"açıklams"
    },
    {
        "Başlık":"basşılk",
        "Açıklama":"açıklams"
    },
    {
        "Başlık":"basşılk",
        "Açıklama":"açıklams"
    },
    {
        "Başlık":"basşılk",
        "Açıklama":"açıklams"
    }
]